spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:sa
    username: ITSOLDEMO
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: hoanggiap6984@gmail.com
#    password: anhgiap123
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true